# Generated by Django 5.1.2 on 2024-10-25 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DobrzeZObcymGdySieDobrzeZna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole_gdzie_te_po_przecinku_sa', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ZDeszczuPodRynne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literkowe_pole', models.CharField(max_length=100)),
                ('numerkowe_pole', models.IntegerField()),
                ('pole_klucza_nie_z_tej_ziemi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MotykaNaSlonce.dobrzezobcymgdysiedobrzezna')),
            ],
        ),
    ]
